name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Push
  run: |
       echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
       docker build . --tag ghcr.io/mysticrenji/react-netcore:$GITHUB_SHA
       docker push ghcr.io/mysticrenji/react-netcore:$GITHUB_SHA
